### ISSUE TITLE
Do not use set-output

### ISSUE THREAD

**Issue by ridomin** [dotnet/nbgv#54]
Actions using `dotnet/nbgv@master` show warnings related to this announcement

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by AArnott** [comment]
If you can confirm this fix works for you in the `master` branch, I'll merge the changes into the `v0.4` stable branch as well.

**Comment by bjorhn** [comment]
@AArnott I can confirm that it works, just tested it out in master.

**Comment by AArnott** [comment]
Thanks. It looks like I already pushed the update to the v0.4 branch a while back, so that should be good too.

**Comment by bjorhn** [comment]
That's odd, yesterday I was still getting the warning when using v0.4, but not when using master. Looking at the gh logs it seems fine today. Sorry about that, will give the issue another bump if it happens again but I probably just made a mistake!
